### PR TITLE
add feature 'delete profile'

### PR DESCRIPTION
**Pull request by KkEi34**
Delete profile feature:
nmprc -d <profile-name>

Active profile can't be deleted.

### CODE REVIEW

**Comment by apastel** [comment]
Why was this PR closed? Was hoping for this feature... :disappointed:

**Comment by KkEi34** [comment]
check <https://github.com/KkEi34/npmrc>. the feature is there.

**Comment by apastel** [comment]
Well cool I'm glad it exists in a fork at least, but why not get it merged into the main repo?

**Comment by KkEi34** [comment]
no permissions - i'm not one of those guys <https://github.com/deoxxa/npmrc/graphs/contributors>.  if you can make a merge & publish a new package i'm happy to create a new PR.
until then to use the feature feel free to install directly from the repo: `npm install -g https://github.com/KkEi34/npmrc`

**Pull request closed without merging**
